(function () {
    const ORDINARY_PATHS = ['bgColor','textColor','useIndependentPadding','paddingUnified','paddingTop','paddingRight','paddingBottom','paddingLeft','borderEnabled','borderColor','borderAlpha','borderWidth','radiusUnified','radiusSingle.tl','radiusSingle.tr','radiusSingle.br','radiusSingle.bl','radiusContinuous.first.tl','radiusContinuous.first.tr','radiusContinuous.first.br','radiusContinuous.first.bl','radiusContinuous.middle.tl','radiusContinuous.middle.tr','radiusContinuous.middle.br','radiusContinuous.middle.bl','radiusContinuous.last.tl','radiusContinuous.last.tr','radiusContinuous.last.br','radiusContinuous.last.bl','blur','opacity','shadowEnabled','shadowColor','shadowAlpha','shadowBlur','shadowSpread','fontSize','backgroundImage','deco1.enabled','deco1.url','deco1.size','deco1.x','deco1.y','deco1.lastOnly','deco2.enabled','deco2.url','deco2.size','deco2.x','deco2.y','deco2.lastOnly'];
    const VOICE_PATHS = ['bgColor','waveColor','timeColor','lengthRatio','iconSize','useIndependentPadding','paddingUnified','paddingTop','paddingRight','paddingBottom','paddingLeft','borderEnabled','borderColor','borderAlpha','borderWidth','radiusUnified','radiusSingle.tl','radiusSingle.tr','radiusSingle.br','radiusSingle.bl','radiusContinuous.first.tl','radiusContinuous.first.tr','radiusContinuous.first.br','radiusContinuous.first.bl','radiusContinuous.middle.tl','radiusContinuous.middle.tr','radiusContinuous.middle.br','radiusContinuous.middle.bl','radiusContinuous.last.tl','radiusContinuous.last.tr','radiusContinuous.last.br','radiusContinuous.last.bl','blur','opacity','shadowEnabled','shadowColor','shadowAlpha','shadowBlur','shadowSpread','fontSize','backgroundImage','deco1.enabled','deco1.url','deco1.size','deco1.x','deco1.y','deco1.lastOnly','deco2.enabled','deco2.url','deco2.size','deco2.x','deco2.y','deco2.lastOnly'];
    const QUOTED_PATHS = ['lineColor','textColor','lineWidth','bgOpacity','radius','fontSize','topMargin'];
    const TOPBAR_PATHS = ['bgColor','textColor','iconColor','bgOpacity','blur','height','dividerColor','dividerOpacity','dividerWidth','backgroundImage','backIconUrl','fireIconUrl','settingsIconUrl','shadowEnabled','shadowColor','shadowOpacity','shadowBlur'];
    const BOTTOMBAR_PATHS = ['barBgColor','inputBgColor','iconColor','barOpacity','blur','inputRadius','inputHeight','inputBorderColor','inputBorderWidth','dividerColor','dividerOpacity','dividerWidth','backgroundImage','menuIconUrl','stickerIconUrl','replyIconUrl'];

    const uiState = { ordinaryRole: 'other', voiceRole: 'other', quotedRole: 'other' };
    const styleState = createDefaultState();
    let previewStyleEl = null;

    function clone(value) { return JSON.parse(JSON.stringify(value)); }
    function mergeDeep(target, source) { Object.keys(source || {}).forEach(function (key) { const next = source[key]; if (next && typeof next === 'object' && !Array.isArray(next)) { if (!target[key] || typeof target[key] !== 'object' || Array.isArray(target[key])) target[key] = {}; mergeDeep(target[key], next); } else target[key] = next; }); return target; }
    function createBubble(overrides) { return mergeDeep({ bgColor: '#ffffff', textColor: '#1c1c1e', useIndependentPadding: true, paddingUnified: 12, paddingTop: 12, paddingRight: 16, paddingBottom: 12, paddingLeft: 16, borderEnabled: false, borderColor: '#d1d1d6', borderAlpha: 18, borderWidth: 1, radiusMode: 'single', radiusUnified: 20, radiusSingle: { tl: 20, tr: 20, br: 20, bl: 4 }, radiusContinuous: { first: { tl: 20, tr: 20, br: 20, bl: 4 }, middle: { tl: 20, tr: 20, br: 20, bl: 20 }, last: { tl: 20, tr: 20, br: 20, bl: 4 } }, blur: 0, opacity: 100, shadowEnabled: false, shadowColor: '#000000', shadowAlpha: 8, shadowBlur: 10, shadowSpread: 0, fontSize: 16, backgroundImage: '', deco1: { enabled: false, url: '', size: 36, x: 0, y: 0, lastOnly: false }, deco2: { enabled: false, url: '', size: 36, x: 0, y: 0, lastOnly: false } }, overrides || {}); }
    function createVoice(overrides) { return mergeDeep(createBubble({ waveColor: '#1c1c1e', timeColor: '#1c1c1e', lengthRatio: 60, iconSize: 20, fontSize: 14 }), overrides || {}); }
    function createDefaultState() {
        return {
            ordinary: { other: createBubble({ shadowEnabled: true, shadowAlpha: 5, shadowBlur: 2 }), user: createBubble({ bgColor: '#333333', textColor: '#ffffff', radiusSingle: { tl: 20, tr: 20, br: 4, bl: 20 }, radiusContinuous: { first: { tl: 20, tr: 20, br: 4, bl: 20 }, middle: { tl: 20, tr: 20, br: 20, bl: 20 }, last: { tl: 20, tr: 20, br: 4, bl: 20 } } }) },
            voice: { other: createVoice({ shadowEnabled: true, shadowAlpha: 5, shadowBlur: 2 }), user: createVoice({ bgColor: '#333333', textColor: '#ffffff', waveColor: '#ffffff', timeColor: '#ffffff', radiusSingle: { tl: 20, tr: 20, br: 4, bl: 20 }, radiusContinuous: { first: { tl: 20, tr: 20, br: 4, bl: 20 }, middle: { tl: 20, tr: 20, br: 20, bl: 20 }, last: { tl: 20, tr: 20, br: 4, bl: 20 } } }) },
            quoted: { other: { lineColor: '#c7c7cc', textColor: '#6e6e73', lineWidth: 3, bgOpacity: 62, radius: 12, fontSize: 12, topMargin: 6 }, user: { lineColor: '#8e8e93', textColor: '#ffffff', lineWidth: 3, bgOpacity: 18, radius: 12, fontSize: 12, topMargin: 6 } },
            layout: { bubbleGap: 12 },
            topbar: { bgColor: '#ffffff', textColor: '#1c1c1e', iconColor: '#1c1c1e', bgOpacity: 75, blur: 20, height: 44, dividerColor: '#000000', dividerOpacity: 8, dividerWidth: 1, backgroundImage: '', backIconUrl: '', fireIconUrl: '', settingsIconUrl: '', shadowEnabled: true, shadowColor: '#000000', shadowOpacity: 3, shadowBlur: 8 },
            bottombar: { barBgColor: '#ffffff', inputBgColor: '#ffffff', iconColor: '#8f8f96', barOpacity: 75, blur: 20, inputRadius: 18, inputHeight: 36, inputBorderColor: '#d3d3da', inputBorderWidth: 1.5, dividerColor: '#000000', dividerOpacity: 8, dividerWidth: 1, backgroundImage: '', menuIconUrl: '', stickerIconUrl: '', replyIconUrl: '' }
        };
    }
    function getByPath(obj, path) { return String(path).split('.').reduce(function (current, key) { return current == null ? undefined : current[key]; }, obj); }
    function setByPath(obj, path, value) { const parts = String(path).split('.'); let current = obj; for (let i = 0; i < parts.length - 1; i += 1) { if (!current[parts[i]] || typeof current[parts[i]] !== 'object') current[parts[i]] = {}; current = current[parts[i]]; } current[parts[parts.length - 1]] = value; }
    function clamp(value, min, max) { const number = Number(value); if (!Number.isFinite(number)) return min; return Math.min(max, Math.max(min, number)); }
    function rgba(color, opacity) { const raw = String(color || '').trim(); if (!raw) return 'rgba(0,0,0,' + (clamp(opacity, 0, 100) / 100) + ')'; if (/^rgba?\(/i.test(raw)) return raw; let hex = raw.replace('#', ''); if (hex.length === 3) hex = hex.split('').map(function (ch) { return ch + ch; }).join(''); const parsed = parseInt(hex, 16); if (Number.isNaN(parsed)) return raw; return 'rgba(' + ((parsed >> 16) & 255) + ', ' + ((parsed >> 8) & 255) + ', ' + (parsed & 255) + ', ' + (clamp(opacity, 0, 100) / 100) + ')'; }
    function normalizeUrl(value) { return String(value == null ? '' : value).trim(); }
    function cssUrl(value) { const normalized = normalizeUrl(value); return normalized ? 'url("' + normalized.replace(/\\/g, '\\\\').replace(/"/g, '\\"') + '")' : 'none'; }
    function bgStack(color, opacity, imageUrl) { const tint = rgba(color, opacity); const image = cssUrl(imageUrl); return image === 'none' ? 'linear-gradient(' + tint + ',' + tint + ')' : 'linear-gradient(' + tint + ',' + tint + '), ' + image; }
    function padValue(state) { return state.useIndependentPadding ? [state.paddingTop, state.paddingRight, state.paddingBottom, state.paddingLeft].map(function (value) { return Math.round(value) + 'px'; }).join(' ') : Math.round(state.paddingUnified) + 'px'; }
    function borderValue(enabled, width, color, alpha) { return !enabled || Number(width) <= 0 ? 'none' : Number(width) + 'px solid ' + rgba(color, alpha); }
    function shadowValue(enabled, color, alpha, blur, spread) { return enabled ? '0 0 ' + Number(blur) + 'px ' + Number(spread) + 'px ' + rgba(color, alpha) : 'none'; }
    function radiusValue(radius) { return [radius.tl, radius.tr, radius.br, radius.bl].map(function (value) { return Math.round(value) + 'px'; }).join(' '); }
    function ensurePreviewStyle() { if (!previewStyleEl) { previewStyleEl = document.getElementById('studio-toolbar-live-preview'); if (!previewStyleEl) { previewStyleEl = document.createElement('style'); previewStyleEl.id = 'studio-toolbar-live-preview'; document.head.appendChild(previewStyleEl); } } return previewStyleEl; }
    function getScreen() { return document.getElementById('studio-chat-screen'); }
    function setVars(screen) { screen.style.setProperty('--studio-topbar-height', clamp(styleState.topbar.height, 28, 88) + 'px'); screen.style.setProperty('--studio-topbar-blur', clamp(styleState.topbar.blur, 0, 50) + 'px'); screen.style.setProperty('--studio-bottombar-blur', clamp(styleState.bottombar.blur, 0, 50) + 'px'); screen.style.setProperty('--studio-bottom-input-height', clamp(styleState.bottombar.inputHeight, 24, 72) + 'px'); screen.style.setProperty('--studio-bottom-input-radius', clamp(styleState.bottombar.inputRadius, 0, 40) + 'px'); screen.style.setProperty('--studio-bubble-gap', clamp(styleState.layout.bubbleGap, 0, 40) + 'px'); }
    function radiusRules(rowSelector, bubbleSelector, state) { const base = '#studio-chat-screen ' + rowSelector + ' ' + bubbleSelector; if (state.radiusMode === 'unified') return base + '{border-radius:' + Math.round(state.radiusUnified) + 'px !important;}'; if (state.radiusMode === 'single') return base + '{border-radius:' + radiusValue(state.radiusSingle) + ' !important;}'; return [ base + '{border-radius:' + radiusValue(state.radiusSingle) + ' !important;}', '#studio-chat-screen ' + rowSelector + '[data-series-slot="first"] ' + bubbleSelector + '{border-radius:' + radiusValue(state.radiusContinuous.first) + ' !important;}', '#studio-chat-screen ' + rowSelector + '[data-series-slot="middle"] ' + bubbleSelector + '{border-radius:' + radiusValue(state.radiusContinuous.middle) + ' !important;}', '#studio-chat-screen ' + rowSelector + '[data-series-slot="last"] ' + bubbleSelector + '{border-radius:' + radiusValue(state.radiusContinuous.last) + ' !important;}', '#studio-chat-screen ' + rowSelector + '[data-series-count="1"] ' + bubbleSelector + '{border-radius:' + Math.round(state.radiusContinuous.first.tl) + 'px ' + Math.round(state.radiusContinuous.first.tr) + 'px ' + Math.round(state.radiusContinuous.last.br) + 'px ' + Math.round(state.radiusContinuous.last.bl) + 'px !important;}' ].join('\n'); }
    function decoRules(rowSelector, bubbleSelector, pseudo, deco) { const base = '#studio-chat-screen ' + rowSelector + ' ' + bubbleSelector + '::' + pseudo; const url = normalizeUrl(deco.url); if (!deco.enabled || !url) return base + '{content:none !important;}'; const target = deco.lastOnly ? '#studio-chat-screen ' + rowSelector + '[data-series-slot="last"] ' + bubbleSelector + '::' + pseudo + ', #studio-chat-screen ' + rowSelector + '[data-series-count="1"] ' + bubbleSelector + '::' + pseudo : base; const anchor = pseudo === 'before' ? 'top:0 !important; right:0 !important;' : 'left:0 !important; bottom:0 !important;'; return base + '{content:none !important;}\n' + target + '{content:"" !important; width:' + clamp(deco.size, 10, 220) + 'px !important; height:' + clamp(deco.size, 10, 220) + 'px !important; ' + anchor + ' transform:translate(' + (Number(deco.x) || 0) + 'px,' + (Number(deco.y) || 0) + 'px) !important; background-image:' + cssUrl(url) + ' !important; background-repeat:no-repeat !important; background-position:center !important; background-size:contain !important; pointer-events:none !important; z-index:2 !important;}'; }
    function bubbleRules(rowSelector, bubbleSelector, state, voice) { const base = '#studio-chat-screen ' + rowSelector + ' ' + bubbleSelector; const lines = [ base + '{background-image:' + bgStack(state.bgColor, state.opacity, state.backgroundImage) + ' !important; background-color:transparent !important; background-size:cover !important; background-position:center !important; background-repeat:no-repeat !important; color:' + state.textColor + ' !important; padding:' + padValue(state) + ' !important; border:' + borderValue(state.borderEnabled, state.borderWidth, state.borderColor, state.borderAlpha) + ' !important; box-shadow:' + shadowValue(state.shadowEnabled, state.shadowColor, state.shadowAlpha, state.shadowBlur, state.shadowSpread) + ' !important; -webkit-backdrop-filter:blur(' + clamp(state.blur, 0, 50) + 'px) !important; backdrop-filter:blur(' + clamp(state.blur, 0, 50) + 'px) !important; font-size:' + clamp(state.fontSize, 10, 24) + 'px !important;}', radiusRules(rowSelector, bubbleSelector, state), decoRules(rowSelector, bubbleSelector, 'before', state.deco1), decoRules(rowSelector, bubbleSelector, 'after', state.deco2) ]; if (voice) { lines.push('#studio-chat-screen ' + rowSelector + ' .voice-bar-top{min-width:' + Math.round(72 + clamp(state.lengthRatio, 10, 100) * 1.2) + 'px !important;}'); lines.push('#studio-chat-screen ' + rowSelector + ' .voice-bar{background:' + state.waveColor + ' !important; opacity:0.82 !important;}'); lines.push('#studio-chat-screen ' + rowSelector + ' .voice-icon-box i{color:' + state.timeColor + ' !important; font-size:' + clamp(state.iconSize, 12, 40) + 'px !important;}'); lines.push('#studio-chat-screen ' + rowSelector + ' .voice-dur-text, #studio-chat-screen ' + rowSelector + ' .voice-time{color:' + state.timeColor + ' !important; font-size:' + clamp(state.fontSize, 10, 22) + 'px !important;}'); lines.push('#studio-chat-screen ' + rowSelector + ' .voice-text-bottom, #studio-chat-screen ' + rowSelector + ' .transcription{color:' + state.timeColor + ' !important; font-size:' + clamp(state.fontSize, 10, 22) + 'px !important; border-top-color:' + rgba(state.timeColor, rowSelector.indexOf('.user') > -1 ? 24 : 16) + ' !important;}'); } return lines.join('\n'); }
    function quoteRules(role, state) { return '#studio-chat-screen .chat-message.' + role + '[data-has-reply="true"] .quote-container{margin-top:' + clamp(state.topMargin, 0, 24) + 'px !important; border-left:' + clamp(state.lineWidth, 1, 10) + 'px solid ' + state.lineColor + ' !important; border-radius:' + clamp(state.radius, 0, 24) + 'px !important; background:' + rgba(role === 'user' ? '#000000' : '#ffffff', state.bgOpacity) + ' !important; color:' + state.textColor + ' !important; font-size:' + clamp(state.fontSize, 10, 18) + 'px !important;}'; }
    function topbarRules(state) { return [ '#studio-chat-screen .chat-header{height:calc(max(47px, env(safe-area-inset-top, 0px)) + var(--studio-topbar-height)) !important; background-image:' + bgStack(state.bgColor, state.bgOpacity, state.backgroundImage) + ' !important; background-color:transparent !important; -webkit-backdrop-filter:blur(var(--studio-topbar-blur)) !important; backdrop-filter:blur(var(--studio-topbar-blur)) !important; border-bottom:' + borderValue(Number(state.dividerWidth) > 0, state.dividerWidth, state.dividerColor, state.dividerOpacity) + ' !important; box-shadow:' + (state.shadowEnabled ? ('0 1px ' + clamp(state.shadowBlur, 0, 40) + 'px ' + rgba(state.shadowColor, state.shadowOpacity)) : 'none') + ' !important;}', '#studio-chat-screen .chat-header-main{top:calc(max(47px, env(safe-area-inset-top, 0px)) + ' + (clamp(state.height, 28, 88) / 2) + 'px) !important;}', '#studio-chat-screen #studio-chat-messages.chat-body{padding-top:calc(max(47px, env(safe-area-inset-top, 0px)) + ' + (clamp(state.height, 28, 88) + 12) + 'px) !important;}', '#studio-chat-screen #studio-chat-title{color:' + state.textColor + ' !important;}', '#studio-chat-screen .chat-topbar-status{color:' + rgba(state.textColor, 55) + ' !important;}', '#studio-chat-screen .chat-header .back-btn, #studio-chat-screen .chat-header .wechat-icon-btn, #studio-chat-screen .chat-header .multi-select-cancel, #studio-chat-screen .chat-topbar-avatar{color:' + state.iconColor + ' !important;}', '#studio-chat-screen .chat-topbar-avatar{background:' + rgba(state.iconColor, 8) + ' !important;}' ].join('\n'); }
    function bottomRules(state) { return [ '#studio-chat-screen .chat-input-area{background-image:' + bgStack(state.barBgColor, state.barOpacity, state.backgroundImage) + ' !important; background-color:transparent !important; -webkit-backdrop-filter:blur(var(--studio-bottombar-blur)) !important; backdrop-filter:blur(var(--studio-bottombar-blur)) !important; border-top:' + borderValue(Number(state.dividerWidth) > 0, state.dividerWidth, state.dividerColor, state.dividerOpacity) + ' !important;}', '#studio-chat-screen .chat-input-shell{background:' + state.inputBgColor + ' !important; border:' + clamp(state.inputBorderWidth, 0, 6) + 'px solid ' + state.inputBorderColor + ' !important; border-radius:var(--studio-bottom-input-radius) !important; height:var(--studio-bottom-input-height) !important;}', '#studio-chat-screen #studio-chat-input::placeholder{color:' + rgba(state.iconColor, 60) + ' !important;}', '#studio-chat-screen .chat-icon-btn, #studio-chat-screen .chat-input-inline-btn, #studio-chat-screen #studio-trigger-ai-reply-btn, #studio-chat-screen #studio-sticker-btn{color:' + state.iconColor + ' !important;}', '#studio-chat-screen #studio-chat-more-btn{background:' + rgba(state.iconColor, 10) + ' !important;}' ].join('\n'); }
    function buildCss() { return [ bubbleRules('.chat-message.other[data-preview-group="ordinary"]', '.message-content', styleState.ordinary.other, false), bubbleRules('.chat-message.user[data-preview-group="ordinary"]', '.message-content', styleState.ordinary.user, false), bubbleRules('.chat-message.other[data-preview-group="voice"]', '.message-content.voice-msg', styleState.voice.other, true), bubbleRules('.chat-message.user[data-preview-group="voice"]', '.message-content.voice-msg', styleState.voice.user, true), quoteRules('other', styleState.quoted.other), quoteRules('user', styleState.quoted.user), topbarRules(styleState.topbar), bottomRules(styleState.bottombar) ].join('\n'); }
    function clearIcon(element, hideWhenEmpty) { if (!element) return; delete element.dataset.studioCustomIcon; element.style.backgroundImage = ''; element.style.backgroundRepeat = ''; element.style.backgroundPosition = ''; element.style.backgroundSize = ''; if (hideWhenEmpty) element.classList.add('hidden'); }
    function applyIcon(element, url, hideWhenEmpty, size) { if (!element) return; const normalized = normalizeUrl(url); if (!normalized) { clearIcon(element, hideWhenEmpty); return; } element.dataset.studioCustomIcon = 'true'; element.style.backgroundImage = 'url("' + normalized.replace(/\\/g, '\\\\').replace(/"/g, '\\"') + '")'; element.style.backgroundRepeat = 'no-repeat'; element.style.backgroundPosition = 'center'; element.style.backgroundSize = size || '68% auto'; if (hideWhenEmpty) element.classList.remove('hidden'); }
    function applyPreview() { const screen = getScreen(); if (!screen) return; setVars(screen); ensurePreviewStyle().textContent = buildCss(); applyIcon(document.getElementById('close-studio-app'), styleState.topbar.backIconUrl, false); applyIcon(document.getElementById('studio-chat-settings-btn'), styleState.topbar.settingsIconUrl, false); applyIcon(document.getElementById('studio-chat-topbar-avatar-right'), styleState.topbar.fireIconUrl, true, '100% 100%'); applyIcon(document.getElementById('studio-chat-more-btn'), styleState.bottombar.menuIconUrl, false); applyIcon(document.getElementById('studio-sticker-btn'), styleState.bottombar.stickerIconUrl, false); applyIcon(document.getElementById('studio-trigger-ai-reply-btn'), styleState.bottombar.replyIconUrl, false); }
    function findDisplay(input) { if (!input) return null; if (input.type === 'color' && input.parentElement) return input.parentElement.querySelector('.value-display'); let current = input.previousElementSibling; while (current) { if (current.classList && current.classList.contains('control-label')) return current.querySelector('.value-display'); current = current.previousElementSibling; } return null; }
    function detectUnit(text) { if (!text) return ''; if (/%\s*$/.test(text)) return '%'; if (/px\s*$/.test(text)) return 'px'; return ''; }
    function formatNumber(value) { const number = Number(value); if (!Number.isFinite(number)) return '0'; if (Number.isInteger(number)) return String(number); return String(Math.round(number * 100) / 100).replace(/\.0+$/, '').replace(/(\.\d*[1-9])0+$/, '$1'); }
    function updateDisplay(binding) { if (!binding.display) return; if (binding.input.type === 'color') binding.display.textContent = String(binding.input.value || '').toUpperCase(); else if (binding.input.type === 'range') binding.display.textContent = formatNumber(binding.input.value) + binding.unit; }
    function readValue(input) { if (input.type === 'checkbox') return !!input.checked; if (input.type === 'range') return Number(input.value); return input.value; }
    function writeValue(binding, value) { if (binding.input.type === 'checkbox') binding.input.checked = !!value; else binding.input.value = value == null ? '' : String(value); updateDisplay(binding); }
    function ensureBubbleGapControls(root) {
        [
            { sectionId: 'sec-ordinary', suffix: 'ordinary' },
            { sectionId: 'sec-voice', suffix: 'voice' }
        ].forEach(function (entry) {
            const section = root.getElementById(entry.sectionId);
            const container = section && section.querySelector('.settings-container');
            if (!container || container.querySelector('[data-studio-bubble-gap-group="' + entry.suffix + '"]')) return;
            const group = document.createElement('div');
            group.className = 'control-group';
            group.setAttribute('data-studio-bubble-gap-group', entry.suffix);
            group.innerHTML = '<div class="control-label"><span>\u6bcf\u6761\u6c14\u6ce1\u95f4\u8ddd</span><span class="value-display" data-studio-bubble-gap-display="true">12px</span></div><input type="range" min="0" max="32" value="12" data-studio-bubble-gap-input="true">';
            container.appendChild(group);
        });
    }
    function syncBubbleGapControls(root) {
        const value = clamp(styleState.layout.bubbleGap, 0, 40);
        root.querySelectorAll('[data-studio-bubble-gap-input="true"]').forEach(function (input) { input.value = String(value); });
        root.querySelectorAll('[data-studio-bubble-gap-display="true"]').forEach(function (display) { display.textContent = formatNumber(value) + 'px'; });
    }
    function bindBubbleGapControls(root) {
        root.querySelectorAll('[data-studio-bubble-gap-input="true"]').forEach(function (input) {
            if (input.dataset.studioBubbleGapBound === 'true') return;
            input.dataset.studioBubbleGapBound = 'true';
            const handler = function () {
                styleState.layout.bubbleGap = clamp(input.value, 0, 40);
                syncBubbleGapControls(root);
                applyPreview();
            };
            input.addEventListener('input', handler);
            input.addEventListener('change', handler);
        });
        syncBubbleGapControls(root);
    }
    function attachBindings(root, sectionId, paths, resolveTarget) { const section = root.getElementById(sectionId); if (!section) return []; const inputs = Array.from(section.querySelectorAll('input')); return paths.map(function (path, index) { const input = inputs[index]; if (!input) return null; const binding = { path: path, input: input, display: findDisplay(input), unit: detectUnit((findDisplay(input) && findDisplay(input).textContent) || '') }; const handler = function () { setByPath(resolveTarget(), path, readValue(input)); updateDisplay(binding); applyPreview(); }; if (input.type === 'checkbox') input.addEventListener('change', handler); else { input.addEventListener('input', handler); if (input.type === 'text') input.addEventListener('change', handler); } updateDisplay(binding); return binding; }).filter(Boolean); }
    function loadBindings(bindings, state) { bindings.forEach(function (binding) { writeValue(binding, getByPath(state, binding.path)); }); }
    function setRoleSegments(section, role) { const control = section && section.querySelector('.segmented-control'); if (!control) return; control.querySelectorAll('.segment').forEach(function (segment, index) { segment.classList.toggle('active', index === (role === 'other' ? 0 : 1)); }); }
    function syncToggle(root, checkboxId, panelId, checked) { const checkbox = root.getElementById(checkboxId); const panel = root.getElementById(panelId); if (!checkbox || !panel) return; checkbox.checked = !!checked; panel.classList.toggle('open', !!checked); }
    function syncMutex(root, checkboxId, unifiedId, independentId, checked) { const checkbox = root.getElementById(checkboxId); const unified = root.getElementById(unifiedId); const independent = root.getElementById(independentId); if (!checkbox || !unified || !independent) return; checkbox.checked = !!checked; unified.classList.toggle('open', !checked); independent.classList.toggle('open', !!checked); }
    function syncMode(root, tabsId, unifiedId, singleId, continuousId, mode) { const tabs = root.getElementById(tabsId); const unified = root.getElementById(unifiedId); const single = root.getElementById(singleId); const continuous = root.getElementById(continuousId); if (!tabs || !unified || !single || !continuous) return; tabs.querySelectorAll('.segment').forEach(function (segment) { segment.classList.toggle('active', segment.getAttribute('data-mode') === mode); }); unified.classList.toggle('open', mode === 'unified'); single.classList.toggle('open', mode === 'single'); continuous.classList.toggle('open', mode === 'continuous'); }
    function syncOrdinary(root, bindings) { const section = root.getElementById('sec-ordinary'); const state = styleState.ordinary[uiState.ordinaryRole]; setRoleSegments(section, uiState.ordinaryRole); loadBindings(bindings, state); syncMutex(root, 'togglePadding', 'panelUnifiedPadding', 'panelIndependentPadding', state.useIndependentPadding); syncToggle(root, 'toggleBorder', 'panelBorder', state.borderEnabled); syncToggle(root, 'toggleShadow', 'panelShadow', state.shadowEnabled); syncToggle(root, 'toggleDeco1', 'panelDeco1', state.deco1.enabled); syncToggle(root, 'toggleDeco2', 'panelDeco2', state.deco2.enabled); syncMode(root, 'radiusModeTabsOrd', 'panelRadiusUnifiedOrd', 'panelRadiusSingleOrd', 'panelRadiusContinuousOrd', state.radiusMode); }
    function syncVoice(root, bindings) { const section = root.getElementById('sec-voice'); const state = styleState.voice[uiState.voiceRole]; setRoleSegments(section, uiState.voiceRole); loadBindings(bindings, state); syncMutex(root, 'togglePaddingVoice', 'panelUnifiedPaddingVoice', 'panelIndependentPaddingVoice', state.useIndependentPadding); syncToggle(root, 'toggleBorderVoice', 'panelBorderVoice', state.borderEnabled); syncToggle(root, 'toggleShadowVoice', 'panelShadowVoice', state.shadowEnabled); syncToggle(root, 'toggleDeco1Voice', 'panelDeco1Voice', state.deco1.enabled); syncToggle(root, 'toggleDeco2Voice', 'panelDeco2Voice', state.deco2.enabled); syncMode(root, 'radiusModeTabsVoice', 'panelRadiusUnifiedVoice', 'panelRadiusSingleVoice', 'panelRadiusContinuousVoice', state.radiusMode); }
    function syncQuoted(root, bindings) { const section = root.getElementById('sec-quoted'); setRoleSegments(section, uiState.quotedRole); loadBindings(bindings, styleState.quoted[uiState.quotedRole]); }
    function syncTopbar(root, bindings) { loadBindings(bindings, styleState.topbar); syncToggle(root, 'toggleTopbarShadow', 'panelTopbarShadow', styleState.topbar.shadowEnabled); }
    function syncBottom(root, bindings) { loadBindings(bindings, styleState.bottombar); }
    function bindRoleTabs(root, sectionId, key, sync) { const section = root.getElementById(sectionId); const control = section && section.querySelector('.segmented-control'); if (!control) return; control.querySelectorAll('.segment').forEach(function (segment, index) { segment.addEventListener('click', function () { uiState[key] = index === 0 ? 'other' : 'user'; sync(root); }); }); }
    function bindModeTabs(root, tabsId, resolveState, sync) { const tabs = root.getElementById(tabsId); if (!tabs) return; tabs.querySelectorAll('.segment').forEach(function (segment) { segment.addEventListener('click', function () { resolveState().radiusMode = segment.getAttribute('data-mode') || 'unified'; sync(root); applyPreview(); }); }); }
    function bindShadow(root) {
        if (!root || root.__studioPreviewBound) return;
        root.__studioPreviewBound = true;
        let helperStyle = root.getElementById('studio-toolbar-preview-helper');
        if (!helperStyle) {
            helperStyle = document.createElement('style');
            helperStyle.id = 'studio-toolbar-preview-helper';
            helperStyle.textContent = '.studio-toolbar-panel-backdrop{display:none !important;} .studio-toolbar-stage{overflow:visible !important;}';
            root.appendChild(helperStyle);
        }
        ensureBubbleGapControls(root);
        bindBubbleGapControls(root);
        const ordinaryBindings = attachBindings(root, 'sec-ordinary', ORDINARY_PATHS, function () { return styleState.ordinary[uiState.ordinaryRole]; });
        const voiceBindings = attachBindings(root, 'sec-voice', VOICE_PATHS, function () { return styleState.voice[uiState.voiceRole]; });
        const quotedBindings = attachBindings(root, 'sec-quoted', QUOTED_PATHS, function () { return styleState.quoted[uiState.quotedRole]; });
        const topbarBindings = attachBindings(root, 'sec-topbar', TOPBAR_PATHS, function () { return styleState.topbar; });
        const bottombarBindings = attachBindings(root, 'sec-bottombar', BOTTOMBAR_PATHS, function () { return styleState.bottombar; });
        bindRoleTabs(root, 'sec-ordinary', 'ordinaryRole', function (currentRoot) { syncOrdinary(currentRoot, ordinaryBindings); });
        bindRoleTabs(root, 'sec-voice', 'voiceRole', function (currentRoot) { syncVoice(currentRoot, voiceBindings); });
        bindRoleTabs(root, 'sec-quoted', 'quotedRole', function (currentRoot) { syncQuoted(currentRoot, quotedBindings); });
        bindModeTabs(root, 'radiusModeTabsOrd', function () { return styleState.ordinary[uiState.ordinaryRole]; }, function (currentRoot) { syncOrdinary(currentRoot, ordinaryBindings); });
        bindModeTabs(root, 'radiusModeTabsVoice', function () { return styleState.voice[uiState.voiceRole]; }, function (currentRoot) { syncVoice(currentRoot, voiceBindings); });
        syncOrdinary(root, ordinaryBindings); syncVoice(root, voiceBindings); syncQuoted(root, quotedBindings); syncTopbar(root, topbarBindings); syncBottom(root, bottombarBindings); syncBubbleGapControls(root); applyPreview();
    }
    function waitForShadow() { const host = document.getElementById('studio-toolbar-host'); if (!host || !host.shadowRoot) { requestAnimationFrame(waitForShadow); return; } bindShadow(host.shadowRoot); }
    window.applyStudioToolbarPreview = applyPreview;
    if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', waitForShadow); else waitForShadow();
})();
